export const CATEGORIES_TYPES = {
  FETCHING_CURRENT_CATEGORIES: "categories/FETCHING_CURRENT_CATEGORIES",
  CURRENT_CATEGORIES_SUCCESSFUL_FETCH:
    "categories/CURRENT_CATEGORIES_SUCCESSFUL_FETCH",
  CURRENT_CATEGORIES_FAIL_FETCH: "categories/CURRENT_CATEGORIES_FAIL_FETCH",
};
